### PR TITLE
Survival version update

### LINKED ISSUE #451: False error message
I have just submitted a new version of the survival package to CRAN, and a part of that process is a check of every reverse dependency --- all 808 of them --- to ensure that my changes have not affected another package.   I am then asked to resolve any issues that arise, before the update is accepted.   I actually pre-check all of these before submission to find any errors on my part, it normally takes a full day or more.

The visR package appears to have a check whose only purpose to raise an error whenever I make a change, i.e., the following code in tests/testthat/test-Surv_CSNR
```r
  # WHEN THIS TEST FAILS, THAT IS OUR SIGNAL THAT {survival} HAS BEEN UPDATED ON CRAN!!
  # AT THAT POINT WE SHOULD DO THE FOLLOWING
  # 1. UPDATE THIS UNIT TEST TO ASSURE THERE IS _NO_ ERROR WITH coxph()
  # 2. ADD A MIN VERSION REQUIREMENT FOR THE {survival} PACKAGE
  #    THIS CAN BE DONE IN TWO WAYS:
  #      1. in the DESCRIPTION file
  #      2. using rlang::check_installed("survival", version = <add required version number>)
  testthat::expect_error(survival::coxph(visR::Surv_CNSR() ~ SEX, data = adtte))
```
Please find another way to track changes to my package; using me as your semaphore is impolite.

Terry Therneau, author of survival

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**

* Increased minimum version required for the survival package to v3.4-0

NOTE: v3.4-0 is only available on GH at the moment and will be on CRAN soon. To ensure these CI checks pass I added `Remotes: therneau/survival` to the DESCRIPTION file instructing the install to grab the survival package from GH. We can either merge this PR now and remove this line after survival is on CRAN, or merge it now and just remove this line before the next CRAN release (CRAN doesn't support `Remotes:`).

**If there is an GitHub issue associated with this pull request, please provide link.**

closes #451 

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from main branch. Ensure the pull request branch and your local version match and both have the latest updates from the main branch.
- [ ] If a new function was added, function should be included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true"), covr::report())`. Before you run, begin a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] Has `NEWS.md` been updated with the changes from this pull request under the heading indicating the latest version. If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Has the version number been incremented using `usethis::use_version(which = "dev")` 
- [ ] Run `devtools::build_readme()` to build the `README.md` file.
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

File: tests/testthat/test-Surv_CNSR.R [hunk 1]
```diff
@@ -36,14 +36,7 @@ testthat::test_that("T1.2 The function is compatible with the survival package",
...
 
-  # WHEN THIS TEST FAILS, THAT IS OUR SIGNAL THAT {survival} HAS BEEN UPDATED ON CRAN!!
-  # AT THAT POINT WE SHOULD DO THE FOLLOWING
-  # 1. UPDATE THIS UNIT TEST TO ASSURE THERE IS _NO_ ERROR WITH coxph()
-  # 2. ADD A MIN VERSION REQUIREMENT FOR THE {survival} PACKAGE
-  #    THIS CAN BE DONE IN TWO WAYS:
-  #      1. in the DESCRIPTION file
-  #      2. using rlang::check_installed("survival", version = <add required version number>)
-  testthat::expect_error(survival::coxph(visR::Surv_CNSR() ~ SEX, data = adtte))
+  testthat::expect_error(survival::coxph(visR::Surv_CNSR() ~ SEX, data = adtte), NA)
```
Comment (bailliem) [inline tests/testthat/test-Surv_CNSR.R:39]: Should we include skip_on_cran() for this test?

**Review by bailliem — APPROVED** [review]
Merge now picking up the GitHub version? Add a skip_on_cran for this test?

File: tests/testthat/test-Surv_CNSR.R (hunk 1 above)
Comment (bailliem) [reply tests/testthat/test-Surv_CNSR.R:39]: Second thoughts - skipping docent make sense once the survival update is on cran. Merge now and make sure we add the check to point to cran prior to the next visR release.
