### PR TITLE
Replaced `survfit` call with quo

### LINKED ISSUE #304: tidyme.survfit ( call ) and dependent friends
Daniel proposed to attach the survfit object to the estimated object rather than saving the call inside the dataframe because it might cause issues when users want to use this call and are not working in the associated environment. Another solution is to work with quosures.

### LINKED ISSUE #365: Saved `survfit()` call in `estimate_KM()` discrepancy
When working with non-CDISC data (which many do), it's common that we'll pipe the dataset into a `mutate()` to make a new censoring variable, then pipe that dataset into `estimate_KM()`. Within visR, the call is modified to remove the `.` and replace it with the data set name. How is this call used downstream? Is it ever evaluated? If so, it can frequently return the wrong result.

In the example below, I subset the lung data set and recode the status variable. But the call returned from `estimate_KM()` include a call to `data = lung` (not the modified lung data object). It seems like this is likely to be an error somewhere, I think particularly in the `get_pvalue()` function?

``` r
library(tidyverse)
library(survival)

km <- 
  lung %>%
  filter(sex == 1) %>%
  mutate(status = case_when(status == 2 ~ 0, status == 1 ~ 1)) %>%
  visR::estimate_KM(
    CNSR = "status",
    AVAL = "time",
    strata = "ph.ecog"
  )
km$call
#> survival::survfit(formula = survival::Surv(time, 1 - status) ~ 
#>     ph.ecog, data = lung)
```

<sup>Created on 2022-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
- The call saved in a `survift` object has been replaced with an {rlang} quo. The quo preserves the original calling environment, and this saved environment is used multiple times in downstream functions to evaluate and parse the original call to `survfit()`. (#365) 
- The name of the original data frame passed to `estimate_KM()` is now exported as `.$data_name`.

 (These items can be copied directly into `NEWS.md` when it's ready to merge)

**Did you include unit tests for the proposed change/bug fix (https://testthat.r-lib.org/)?**
Unit tests for `get_pvalue()` have been added as well a unit test for `.$data_name`.

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #365
closes #304

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from main branch. Ensure the pull request branch and your local version match and both have the latest updates from the main branch.
- [ ] If a new function was added, function should be included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true"), covr::report())`. Before you run, begin a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [ ] Has `NEWS.md` been updated with the changes from this pull request under the heading indicating the latest version. If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Has the version number been incremented using `usethis::use_version(which = "dev")` 
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@SHAESEN2 this is pretty close to complete. There is something tricky happening with `get_COX_HR()`: the tests and examples all run interactively, but we hit an error with R CMD Check. I'll look into it again later.

**Comment by ddsjoberg** [comment]
@SHAESEN2 this is now ready for you

**Comment by ddsjoberg** [comment]
A couple of notes that may make review easier:
- `rlang::quo()` is similar to creating an expression, except that it also attached the associated environment as an attribute.
- `rlang::quo_squash()` converts a `quo()` object into an expression. This is used frequently to convert the `survfit()` quo into an expression so we can parse the formula or data objects from the expression or use base `eval()` (which won't work on a quo).
- `rlang::inject()`: this function is essentially `rlang::expr() %>% eval()`; it creates an expression and immediately evaluates it.
- bang-bang: The `!!` operator (or bang-bang) injects an object's value into an expression. See example below

``` r
rlang::expr(x %in% letters[1])
#> x %in% letters[1]
rlang::expr(x %in% !!letters[1])
#> x %in% "a"
```

<sup>Created on 2022-05-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
cc @SHAESEN2

File: R/get_pvalue.R [hunk 1]
```diff
@@ -74,21 +74,22 @@ get_pvalue <- function(survfit_object,
...
     ))),
     `Custom`      = rlang::expr(eval(as.call(
-      append(NewCall, list(rho = rho))
+      append(!!NewCall, list(rho = !!rho))
     )))
   )[ptype]
 
 
-  survdifflist_eval <- lapply(survdifflist, eval, env = environment())
+  survdifflist_eval <-
```
Comment (SHAESEN2) [inline R/get_pvalue.R:91]: We only wish to evaluate what is required. It is to be more efficient.

File: R/estimate_KM.R [hunk 2]
```diff
@@ -65,102 +65,56 @@
...
-  if (is.null(data)) stop(paste0("Data can't be NULL."))
-
-  if (base::length(base::deparse(Call[["data"]])) == 1 && base::deparse(Call[["data"]]) %in% c(".", ".x")){
-    df <- the_lhs()
-    Call[["data"]] <- as.symbol(df)
-  } else {
-     df <- as.character(sub("\\[.*$", "", deparse(dfExpr))[1])
-  }
-
-  if (!(inherits(data, "data.frame") | inherits(data, "tibble") | inherits(data, "data.table"))) stop(paste0("Data can be of `class` dataframe or tibble or data.table."))
```
Comment (SHAESEN2) [inline R/estimate_KM.R:96]: Test needs to be included

File: R/estimate_KM.R [hunk 3]
```diff
@@ -65,102 +65,56 @@
...
-
-  data <- as.data.frame(data)
-
-# Validate columns --------------------------------------------------------
```
Comment (SHAESEN2) [inline R/estimate_KM.R:100]: keep comments (throughout document)

File: R/estimate_KM.R [hunk 4]
```diff
@@ -65,102 +65,56 @@
...
+  if (!is.numeric(data[[AVAL]])){
     stop("Analysis variable (AVAL) is not numeric.")
   }
 
-  if (! is.numeric(data[[CNSR]])){
+  if (!is.numeric(data[[CNSR]])){
     stop("Censor variable (CNSR) is not numeric.")
   }
 
-# Ensure the presence of at least one strata -----------------------------
```
Comment (SHAESEN2) [inline R/estimate_KM.R:116]: I prefer this explicit code section for easy debugging and understanding of what happens rather than to be more compact. Our target audience included SAS programmers that have little experience in R

Comment (SHAESEN2) [reply R/estimate_KM.R:116]: If you prefer formula_rhs instead of main, that is OK for me

File: R/estimate_KM.R [hunk 5]
```diff
@@ -65,102 +65,56 @@
...
 
- ## Reverse censoring: see ADaM guidelines versus R survival KM analysis
+  survfit_object <-
+    rlang::inject(survival::survfit(!!formula, data = data, !!!dots)) %>%
+    survival::survfit0(start.time = 0)
 
-  formula <- stats::as.formula(paste0("survival::Surv(", AVAL, ", 1-", CNSR, ") ~ ", main))
+  # convert survfit() call to quo with attached envir --------------------------
+  survfit_object$call[[1]] <- rlang::expr(survival::survfit) # adding `survival::` prefix
+  survfit_object$call <- rlang::quo(!!survfit_object$call)
```
Comment (SHAESEN2) [inline R/estimate_KM.R:112]: for me to check if environment is also attached or needs to be specified

Comment (SHAESEN2) [reply R/estimate_KM.R:112]: for me to check if ... (ellipsis) is also there

File: R/estimate_KM.R [hunk 6]
```diff
@@ -194,9 +148,18 @@ estimate_KM <- function(
...
 
+  # Return ------------------------------------------------------------------
+  survfit_object
+}
 
-
-# Return ------------------------------------------------------------------
-
-  return(survfit_object)
+.call_list_to_name <- function(call_list) {
```
Comment (SHAESEN2) [inline R/estimate_KM.R:155]: check overlap with the_lhs. We should only keep one.

File: tests/testthat/test-watchdog_testfiles.R [hunk 7]
```diff
@@ -10,6 +10,7 @@
 
 context("validate_watchdog - T1. Details on last change for test files are recorded.")
 # skip on GH Actions and CRAN
+skip_if(tolower(Sys.info()[["user"]]) %in% "sjobergd")
```
Comment (SHAESEN2) [inline tests/testthat/test-watchdog_testfiles.R:13]: remove

File: tests/testthat/test-get_pvalue.R [hunk 8]
```diff
@@ -38,6 +38,24 @@ testthat::test_that("T1.1. No error when a `survfit` object is passed to the fun
 
   survfit_object <- visR::estimate_KM(adtte, strata = "TRTA")
   testthat::expect_error(visR::get_pvalue(survfit_object), NA)
+
+  # testing the p-value is correct when filtered data is piped to estimate_KM()
```
Comment (SHAESEN2) [inline tests/testthat/test-get_pvalue.R:42]: this should be  a new test

Comment (SHAESEN2) [reply tests/testthat/test-get_pvalue.R:42]: also do a test within estimate_KM for this

Comment (SHAESEN2) [reply tests/testthat/test-get_pvalue.R:42]: upcate cox testing too

File: tests/testthat/test-estimate_KM.R [hunk 9]
```diff
@@ -380,36 +380,28 @@ testthat::test_that("T6.4 The function adds strata labels equal to the strata na
...
-
-  ## survival package
-  survobj_survival <- adtte %>%
-    survival::survfit(survival::Surv(AVAL, 1-CNSR) ~ SEX, data = .) %>%
-    survival::survfit0(start.time = 0)
-  call_survival <- as.list(survobj_survival[["call"]])
-
-  ## survival package
-  survobj_visR <- adtte %>%
+testthat::test_that("T7.1 The function updates .$data_name when magrittr pipe is used", {
```
Comment (SHAESEN2) [inline tests/testthat/test-estimate_KM.R:383]: we should do this too with adtte[1:100,] or with double pipe adtte %>% mutate() %>%

**Comment by ddsjoberg** [comment]
> Nice work ! I need to take more time to try it out. I don't mind doing all the updates myself while going through the code.

Thanks @SHAESEN2 ! I'll try to go through your comments and respond before our meeting today (I think I should be able to join)

File: R/estimate_KM.R (hunk 2 above)
Comment (ddsjoberg) [reply R/estimate_KM.R:96]: all those objects (data.frame, tibble, and data.table) include class "data.frame", so I updated this to a single test. Did not remove this.

File: R/estimate_KM.R (hunk 3 above)
Comment (ddsjoberg) [reply R/estimate_KM.R:100]: this still appears in the code, now on line 77

File: R/estimate_KM.R (hunk 4 above)
Comment (ddsjoberg) [reply R/estimate_KM.R:116]: Please feel free to change as you see fit. I will note that `tidyr::drop_na(any_of(c(AVAL, CNSR, strata)))` only uses top-level, user-facing functions: no behind-the-scenes-type functions here

File: R/estimate_KM.R (hunk 6 above)
Comment (ddsjoberg) [reply R/estimate_KM.R:155]: this little function calls `the_lhs()`. I didn't add this code, just moved it into a small helper function.

File: R/get_pvalue.R (hunk 1 above)
Comment (ddsjoberg) [reply R/get_pvalue.R:91]: I didn't try to improve efficiency here, just modified existing code as needed.

File: R/estimate_KM.R (hunk 2 above)
Comment (SHAESEN2) [reply R/estimate_KM.R:96]: I agree

Comment (SHAESEN2) [reply R/estimate_KM.R:96]: I agree

File: R/estimate_KM.R (hunk 6 above)
Comment (SHAESEN2) [reply R/estimate_KM.R:155]: Moved to utils file

File: R/estimate_KM.R [hunk 10]
```diff
@@ -194,9 +148,18 @@ estimate_KM <- function(
       rlang::set_names(strata)
   }
 
+  # Return ------------------------------------------------------------------
```
Comment (SHAESEN2) [inline R/estimate_KM.R:151]: Error in attr(data[[x]], "label") %||% x : could not find function "%||%" Can you look into this? Perhaps we need to increase rlang version?

Comment (SHAESEN2) [inline R/estimate_KM.R:151]: Error in attr(data[[x]], "label") %||% x : could not find function "%||%" Can you look into this? Perhaps we need to increase rlang version?

File: R/estimate_KM.R (hunk 5 above)
Comment (SHAESEN2) [inline R/estimate_KM.R:112]: For me two issues here:

1.  sf <- adtte %>%
  dplyr::filter(TRTA == "Placebo") %>%
  estimate_KM(strata = "SEX")

  > sf
Call: ~survival::survfit(formula = survival::Surv(AVAL, 1 - CNSR) ~ 
    SEX, **data = data**)
I want it to say data = "sf"

2. With this change we are breaking the compatibility with traditional survfit objects. This we wish to avoid. Could we save the environment alone into an argument and then reconstruct the call if an environment is attached? Otherwise we redo the call as we did before?

Comment (SHAESEN2) [inline R/estimate_KM.R:112]: For me two issues here:

1.  sf <- adtte %>%
  dplyr::filter(TRTA == "Placebo") %>%
  estimate_KM(strata = "SEX")

  > sf
Call: ~survival::survfit(formula = survival::Surv(AVAL, 1 - CNSR) ~ 
    SEX, **data = data**)
I want it to say data = "sf"

2. With this change we are breaking the compatibility with traditional survfit objects. This we wish to avoid. Could we save the environment alone into an argument and then reconstruct the call if an environment is attached? Otherwise we redo the call as we did before?

Comment (SHAESEN2) [reply R/estimate_KM.R:112]: OK

File: R/estimate_KM.R [hunk 11]
```diff
@@ -65,101 +65,68 @@
...
 
-  data <- as.data.frame(data) %>%
-    tidyr::drop_na(AVAL, CNSR)
+  data <-
+    as.data.frame(data) %>%
+    tidyr::drop_na(any_of(c(AVAL, CNSR)))
 
   if (!is.null(strata)){
     data <- data %>%
       tidyr::drop_na(any_of({{strata}}))
```
Comment (ddsjoberg) [inline R/estimate_KM.R:108]: Remove the `{{ }}` here. The `strata` object can only be a character vector and you use the curly-curly when working the captured quos

File: R/estimate_KM.R (hunk 5 above)
Comment (ddsjoberg) [reply R/estimate_KM.R:127]: 1. The sf name is saved in `data_name`, not in the quo. The quo must evaluate properly and this would not happen if we changed the data object.
2. I started looking into this, and was happy to see that everything works wit the `survfit()` object as well. There was only once instance I tested that errored and that is when the survfit object is created like `data %>% filter() %>% survfit(one ~ two, data = .)`, `get_pvalue()` is later called on the object. BUT this has never worked in the package, and is a key example of when you need the correct envir specified to evaluated.

File: R/estimate_KM.R (hunk 10 above)
Comment (ddsjoberg) [reply R/estimate_KM.R:168]: It is working on my machine and on GH Actions. What notes/errors do you see when you run R CMD Check locally?

File: R/estimate_KM.R (hunk 5 above)
Comment (SHAESEN2) [reply R/estimate_KM.R:127]: The main issue is that I wish to see the correct call when printing the object. data = data is just not informative. Since the mofied dataframe is inside the same environment, I don't see why it can't be captured. Perhaps we should create a new variable with the name of the actual data 'name of original df' <- data and then create the quosure. Would that work?

Comment (SHAESEN2) [reply R/estimate_KM.R:127]: The main issue is that I wish to see the correct call when printing the object. data = data is just not informative. Since the mofied dataframe is inside the same environment, I don't see why it can't be captured. Perhaps we should create a new variable with the name of the actual data 'name of original df' <- data and then create the quosure. Would that work?

Comment (SHAESEN2) [reply R/estimate_KM.R:127]: For the second issue, we need to investigate further. Did you find why it does not work?

Comment (ddsjoberg) [reply R/estimate_KM.R:127]: 1. expressions, quosures, and environments are already difficult to handle. The more we massage them and manipulate them, we are likely to not cover edge cases and will introduce bugs. Also, we don't have a reliable method for extracting the data set symbol, which is why we are here adding quosures and environments: our previous method led to a silent bug when trying to extract the input data set symbol and use it in `get_pvalue()`. The tilda before the quosure is how the are printed and cannot be modified. The raw output from a survfit object isn't useful anyway, so let's not complicate the situation by trying to modifying it.
2. I do know why this doesn't work. If you construct a `survfit()` using `%>%` and `data = .`, the saved call will contain `data = .`. To calculate the p-value, the call is parsed and reconstructed into a `survdiff()` call, but `data = .` can never be recovered. We could improve error messaging in this situation, but there is nothing we can do to avoid the error.

File: R/get_pvalue.R (hunk 1 above)
Comment (ddsjoberg) [reply R/get_pvalue.R:91]: Took a quick look at this. This evaluated list is used multiple times in the section below. I would need to dive deeper into the `get_pvalue()` code to see exactly what is needed and what can be removed. Let's save this for a separate pull request whose aim is to improve efficiency 

```r
 survdifflist_eval <-
    lapply(survdifflist, eval, envir = attr(survfit_object$call, ".Environment"))

# Statlist ----------------------------------------------------------------

  statlist <- unique(statlist)
  statlist <- base::sub("test", "Equality across strata", statlist, fixed = TRUE)
  statlist <- base::sub("pvalue", "p-value", statlist, fixed = TRUE)
  Nms <- names(survdifflist_eval)

  stat_summary <- list(
    `Equality across strata` = rlang::expr(base::sub(
      "Custom",
      paste0("Harrington and Fleming test (rho = ", rho, ")"),
      Nms,
      fixed = TRUE
    )),
    `Chisq`    = rlang::expr(unlist(
      lapply(survdifflist_eval, function(x)
        format(round(x$chisq, 3), nsmall = 3, justify = "right", width = 6, scientific = FALSE)
      ))),
    df        = rlang::expr(unlist(
      lapply(survdifflist_eval, function(x)
        length(x$n) - 1)
    )),
    `p-value` = rlang::expr(unlist(
      lapply(survdifflist_eval, function(x)
        .pvalformat(
          stats::pchisq(x$chisq, length(x$n) - 1, lower.tail = FALSE)
        ))
    ))
  )[statlist]
```

File: tests/testthat/test-get_pvalue.R (hunk 8 above)
Comment (ddsjoberg) [reply tests/testthat/test-get_pvalue.R:42]: Added this test to its own section, and added similar tests in `estimate_KM()` as well. The cox model hasn't been merged yet.

File: tests/testthat/test-estimate_KM.R (hunk 9 above)
Comment (ddsjoberg) [reply tests/testthat/test-estimate_KM.R:383]: I added a test with `adtte[1:100,]`

File: R/estimate_KM.R (hunk 11 above)
Comment (ddsjoberg) [reply R/estimate_KM.R]: I removed the curly brackets

File: R/estimate_KM.R [hunk 12]
```diff
@@ -65,101 +65,68 @@
...
-    survfit_object, start.time = 0
-  )
+  survfit_object <-
+    rlang::inject(survival::survfit(!!formula, data = data, !!!dots)) %>% # immediate resolves call arguments
+    survival::survfit0(start.time = 0)
 
+  # convert survfit() call to quo with attached envir --------------------------
 
-# Update Call with original info and dots, similar as update.default ------
+  survfit_object$call[[1]] <- rlang::expr(survival::survfit) # adding `survival::` prefix
```
Comment (SHAESEN2) [inline R/estimate_KM.R:126]: survfit_object$call[[1]] <- rlang::expr(survival::survfit) # adding `survival::` prefix
  survfit_object$call <- rlang::quo(!!survfit_object$call)

When looking into detail I see the first line is overwritten by the second line of code. One aesthetic issue that bothers me is that the quosure is creating ~ in front of the formula. Do you know why that is introduced? It will confuse less experienced programmers.

File: R/get_pvalue.R (hunk 1 above)
Comment (SHAESEN2) [reply R/get_pvalue.R:91]: OK but then put the original code back. How it is written originally, it create an unevaluated list and only evaluated the required elements.

Comment (ddsjoberg) [reply R/get_pvalue.R:91]: The update I made was to evaluate in the correct environment. You'll need to explain to me how the previous code only evaluated a single call. Let's either join Mondays call early to discuss or stay on after.

File: R/estimate_KM.R (hunk 12 above)
Comment (ddsjoberg) [reply R/estimate_KM.R:126]: The first line just adds the survival prefix to the call ( which we can remove, I left it in as it previously appeared ), the second converts the call to a quosure. Is there an issue with the results?

Comment (SHAESEN2) [reply R/estimate_KM.R:128]: Looking at it again, it makes more sense.

**Comment by SHAESEN2** [comment]
PR is OK for me except for two issues I see:

**Comment by ddsjoberg** [comment]
> PR is OK for me except for two issues I see:
> 
> 1. Below returns a character vs symbol. It would be helpful if we could return the character.
>    survobj <- visR::estimate_KM(data = adtte[adtte$SEX == "F", ], strata = "RACE")
>    testthat::expect_equal(survobj$data_name, "adtte")

I change them to character
 
> 2. There is an error in this PR
> 
> library(visR)
> 
> sf <- adtte %>% dplyr::filter(TRTA == "Placebo") %>% estimate_KM(strata = "SEX")
> 
> Error in .call_list_to_name(as.list(match.call())) : could not find function ".call_list_to_name"

This isn't an issue on my machine or on GitHub Actions.

**Comment by ddsjoberg** [comment]
all checks pass except some Ubuntu builds that are failing to build R; not an issue with the code.
